name: "Wokwi-CI: Build and test examples"

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        example: [hello_world, vga]
        target: [esp32, esp32s2, esp32s3]
    runs-on: ubuntu-latest
    container:
      image: jmeeuws/esp-dlang
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Build examples/${{ matrix.example }}
        run: |
          export HOME=/root
          source /opt/esp-idf/export.sh >/dev/null
          ulimit -n 4096
          cd ./examples/${{ matrix.example }}/
          idf.py set-target ${{ matrix.target }}
          idf.py build
      - name: Setup CI files
        run: |
          cat > wokwi.toml <<EOF
          [wokwi]
          version = 1
          elf = "./examples/${{ matrix.example }}/build/${{ matrix.example }}.elf"
          firmware = "./examples/${{ matrix.example }}/build/${{ matrix.example }}.bin"
          EOF
          cp ./.github/workflows/wokwi/diagram-${{ matrix.target }}.json ./diagram.json
      - uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          timeout: 5000
          expect_text: 'Hello from dlang!'
